services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: php-code-quality-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ~/.cache/composer/:/var/www/.composer/cache:rw
      - ~/.config/composer:/var/www/.composer/auth.json:rw
